# Generated by Django 5.0.7 on 2024-07-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
