# Generated by Django 5.0.7 on 2024-07-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_', '0002_alter_replies_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='date',
            field=models.DateField(),
        ),
    ]
