# Generated by Django 5.0.7 on 2024-07-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_', '0003_alter_replies_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='customer',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
