# Generated by Django 5.0.7 on 2024-07-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_', '0005_users'),
        ('users_', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Templates',
        ),
    ]
