# Generated by Django 5.0.7 on 2024-07-30 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_', '0006_rename_users_templates'),
        ('users_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='username',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users_.user_model'),
        ),
    ]
