# Generated by Django 5.0.7 on 2024-07-30 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_', '0007_alter_templates_username'),
        ('users_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_.user_model'),
        ),
    ]
