# Generated by Django 5.0.7 on 2024-07-31 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_', '0009_alter_templates_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templates',
            old_name='username',
            new_name='template_name',
        ),
    ]
