# Generated by Django 5.0.7 on 2024-08-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_', '0010_rename_username_templates_template_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('img_id', models.CharField(max_length=1000)),
            ],
        ),
    ]
