# Generated by Django 5.0.7 on 2024-08-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_', '0011_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='id',
        ),
        migrations.AlterField(
            model_name='media',
            name='img_id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
