# Generated by Django 5.0.7 on 2024-08-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_', '0012_remove_media_id_alter_media_img_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templates',
            old_name='templates',
            new_name='template_message',
        ),
        migrations.AddField(
            model_name='templates',
            name='template_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
