# Generated by Django 5.0.7 on 2024-08-04 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_', '0013_rename_templates_templates_template_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 4, 8, 38, 1, 827773, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='templates',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='templates',
            name='template_type',
            field=models.CharField(max_length=100),
        ),
    ]
