# Generated by Django 5.0.7 on 2024-08-05 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_', '0014_templates_date_templates_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
                ('tags', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='templates',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 5, 13, 12, 47, 990923, tzinfo=datetime.timezone.utc)),
        ),
    ]
