# Generated by Django 5.0.7 on 2024-08-05 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_', '0015_contact_alter_templates_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='statuss',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='templates',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 5, 13, 29, 31, 796144, tzinfo=datetime.timezone.utc)),
        ),
    ]
