# Generated by Django 5.0.7 on 2024-08-05 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_', '0016_contact_statuss_alter_templates_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='statuss',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='templates',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 5, 13, 30, 4, 533160, tzinfo=datetime.timezone.utc)),
        ),
    ]
